M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 18, Thursday 01:15:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-18T01:15:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X3.5Y28.5
X3.5Y3.5
X88.0Y28.5
X88.0Y3.5
X176.0Y28.5
X176.0Y3.529
X260.5Y28.5
X260.5Y3.5
T0
M30
