M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 18, Thursday 01:13:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-18T01:13:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
G00X4.5Y6.65
M15
G01X4.5Y25.35
M16
G05
G00X238.8Y25.35
M15
G01X238.8Y6.65
M16
G05
T0
M30
